defaults:
  - base_config
  - _self_

devices: [0,1,2,3]
epochs: 500
batch_size: 8

monitor_metric: "val_loss"
monitor_metric_mood: "val_loss_mood"
monitor_metric_va: "val_loss_va"

checkpoint:
  monitor: "${monitor_metric}"
  filename: "{epoch:02d}-{${monitor_metric}:.4f}"
  save_top_k: 5
  mode: "min"
  auto_insert_metric_name: False
  save_last: True

checkpoint_mood:
  monitor: "${monitor_metric_mood}"
  filename: "mood-{epoch:02d}-{${monitor_metric_mood}:.4f}"
  save_top_k: 5
  mode: "min"
  auto_insert_metric_name: False
  save_last: True

checkpoint_va:
  monitor: "${monitor_metric_va}"
  filename: "va-{epoch:02d}-{${monitor_metric_va}:.4f}"
  save_top_k: 5
  mode: "min"
  auto_insert_metric_name: False
  save_last: True

earlystopping:
  monitor: "${monitor_metric}"
  patience: 10
  min_delta: 0.0001
  mode: "min"

trainer:
  devices: ${devices}
  max_epochs: ${epochs}
  accelerator: 'gpu'
